#!/usr/bin/env bash
# installs and configures HAproxy on lb-01 server
apt-get update
apt-get install -y haproxy

init="ENABLED=1"

echo -e "\n$init" >> /etc/default/haproxy

proxy="frontend http
        bind *:80
        mode http

        default_backend web-backend

backend web-backend
        balance roundrobin
        mode http
        server web-01 54.84.61.21:80
        server web-02 52.91.145.40:80"

echo -e "$proxy" >> /etc/haproxy/haproxy.cfg

service haproxy restart
