#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# Your script should only display:username, user id, path for the user

while read line
do
    echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
