#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
minutes=1

while [ $hours -lt 13 ]; do
    while [ $minutes -lt 60 ]; do
        printf "%02d:%02d\n" $hours $minutes
        ((minutes++))
    done
    ((hours++))
    minutes=0
done
